version: '3.8'

services:
  estoqueSoftrack:
    image: mysql
    ports:
      - "3306:3306"
    container_name: EstoqueDataBase
    
    environment:
      MYSQL_DATABASE: estoquedocker
      MYSQL_USER: cliente
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./dataEstoque/data:/var/lib/mysql
    restart: always
    networks:
      - my-network
networks:
  my-network:
    driver: bridge