version: '3.8'

services:
  mysql:
    image: mysqldb
    build: .
    ports:
      - "3306:3306"
    container_name: mysqlGuilherme
    environment:
      MYSQL_DATABASE: estoquedocker
      MYSQL_USER: cliente
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
