-- CreateTable
CREATE TABLE `st_cliente` (
    `ID_CLIENTE` VARCHAR(191) NOT NULL,
    `S_NOME` VARCHAR(45) NULL,
    `S_ATIVO` CHAR(1) NULL DEFAULT 'S',
    `ID_EMPRESA` VARCHAR(191) NOT NULL,

    PRIMARY KEY (`ID_CLIENTE`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `st_empresa` (
    `ID_EMPRESA` VARCHAR(191) NOT NULL,
    `S_NOME` VARCHAR(45) NOT NULL,
    `D_DATA` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
    `S_ATIVO` CHAR(1) NULL DEFAULT 'S',

    PRIMARY KEY (`ID_EMPRESA`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `st_fornecedor` (
    `ID_FORNECEDOR` VARCHAR(191) NOT NULL,
    `S_NOME` VARCHAR(45) NULL,
    `S_ATIVO` CHAR(1) NULL DEFAULT 'S',

    PRIMARY KEY (`ID_FORNECEDOR`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `st_log_acesso` (
    `ID_LOG_ACESSO` VARCHAR(191) NOT NULL,
    `ID_USUARIO` INTEGER NOT NULL,
    `S_EMAIL` VARCHAR(150) NOT NULL,
    `S_PERMITIDO` VARCHAR(1) NOT NULL,
    `D_DATA` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),

    PRIMARY KEY (`ID_LOG_ACESSO`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `st_produto` (
    `ID_PRODUTO` VARCHAR(191) NOT NULL,
    `S_NOME` VARCHAR(150) NULL,
    `S_ATIVO` CHAR(1) NULL DEFAULT 'S',
    `N_SERIAL` VARCHAR(45) NULL,
    `ID_TIPO` VARCHAR(191) NOT NULL,

    PRIMARY KEY (`ID_PRODUTO`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `st_produto_lote` (
    `ID_PRODUTO_LOTE` VARCHAR(191) NOT NULL,
    `N_QUANTIDADE` INTEGER NOT NULL,
    `S_DETALHES` VARCHAR(100) NULL DEFAULT '',
    `S_DIMENSAO` VARCHAR(50) NULL DEFAULT '',
    `N_VALOR` DECIMAL(65, 30) NULL DEFAULT 0,
    `ID_LOTE` VARCHAR(191) NOT NULL,
    `ID_PRODUTO` VARCHAR(191) NOT NULL,

    PRIMARY KEY (`ID_PRODUTO_LOTE`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `st_lote` (
    `ID_LOTE` VARCHAR(191) NOT NULL,
    `D_DATA_INICIO` TIMESTAMP(0) NULL DEFAULT CURRENT_TIMESTAMP(0),
    `S_ATIVO` CHAR(1) NOT NULL DEFAULT 'S',
    `ID_CLIENTE` VARCHAR(191) NULL,
    `ID_FORNECEDOR` VARCHAR(191) NULL,

    UNIQUE INDEX `st_lote_ID_LOTE_key`(`ID_LOTE`),
    PRIMARY KEY (`ID_LOTE`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `st_tipo` (
    `ID_TIPO` VARCHAR(191) NOT NULL,
    `S_NOME` VARCHAR(45) NULL,
    `S_ATIVO` VARCHAR(1) NULL DEFAULT 'S',

    PRIMARY KEY (`ID_TIPO`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `st_grupo` (
    `ID_GRUPO` VARCHAR(191) NOT NULL,
    `S_NOME` VARCHAR(50) NOT NULL,
    `N_NIVEL` INTEGER NULL,
    `S_ATIVO` CHAR(1) NULL DEFAULT 'S',

    PRIMARY KEY (`ID_GRUPO`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `st_usuario` (
    `ID_USUARIO` VARCHAR(191) NOT NULL,
    `S_NOME` VARCHAR(150) NOT NULL,
    `S_EMAIL` VARCHAR(200) NOT NULL,
    `S_SENHA` VARCHAR(64) NOT NULL,
    `D_EXPIRACAO_SENHA` TIMESTAMP(0) NOT NULL,
    `N_TENTATIVAS_LOGIN` INTEGER NULL DEFAULT 0,
    `S_CHAVE` VARCHAR(30) NULL,
    `S_ATIVO` VARCHAR(1) NULL DEFAULT 'S',
    `ID_GRUPO` VARCHAR(191) NOT NULL,

    PRIMARY KEY (`ID_USUARIO`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `st_cliente` ADD CONSTRAINT `st_cliente_ID_EMPRESA_fkey` FOREIGN KEY (`ID_EMPRESA`) REFERENCES `st_empresa`(`ID_EMPRESA`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `st_produto` ADD CONSTRAINT `st_produto_ID_TIPO_fkey` FOREIGN KEY (`ID_TIPO`) REFERENCES `st_tipo`(`ID_TIPO`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `st_produto_lote` ADD CONSTRAINT `st_produto_lote_ID_LOTE_fkey` FOREIGN KEY (`ID_LOTE`) REFERENCES `st_lote`(`ID_LOTE`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `st_produto_lote` ADD CONSTRAINT `st_produto_lote_ID_PRODUTO_fkey` FOREIGN KEY (`ID_PRODUTO`) REFERENCES `st_produto`(`ID_PRODUTO`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `st_lote` ADD CONSTRAINT `st_lote_ID_CLIENTE_fkey` FOREIGN KEY (`ID_CLIENTE`) REFERENCES `st_cliente`(`ID_CLIENTE`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `st_lote` ADD CONSTRAINT `st_lote_ID_FORNECEDOR_fkey` FOREIGN KEY (`ID_FORNECEDOR`) REFERENCES `st_fornecedor`(`ID_FORNECEDOR`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `st_usuario` ADD CONSTRAINT `st_usuario_ID_GRUPO_fkey` FOREIGN KEY (`ID_GRUPO`) REFERENCES `st_grupo`(`ID_GRUPO`) ON DELETE RESTRICT ON UPDATE CASCADE;
